import { createFileRoute } from "@tanstack/react-router";
import { Activity, Files, HardDrive, Sparkles, Zap } from "lucide-react";
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis, CartesianGrid, Line, LineChart } from "recharts";
import { DemoNotice, PageHeading, SectionTitle, StatCard } from "@/components/dedupai/shared";
import { DEMO_INSIGHTS, MOCK_ACTIVITY, MOCK_SAVINGS_TREND, MOCK_STORAGE } from "@/data/mockData";
import { useDedupAI } from "@/components/dedupai/DedupAIProvider";

export const Route = createFileRoute("/analytics")({
  head: () => ({ meta: [
    { title: "Analytics | DedupAI" }, { name: "description", content: "Explore illustrative DedupAI storage efficiency, file classifications, and sample savings trends." },
    { property: "og:title", content: "Analytics | DedupAI" }, { property: "og:description", content: "Detailed sample analytics for the DedupAI storage optimization demo." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" },
  ] }), component: AnalyticsPage,
});

const distribution = [
  { name: "Unique", value: 1044, color: "var(--color-success)" },
  { name: "Duplicate", value: 128, color: "var(--color-info)" },
  { name: "Similar", value: 76, color: "var(--color-warning)" },
];

function AnalyticsPage() {
  const { uploadedFiles } = useDedupAI();
  const unique = (distribution.find((item) => item.name === "Unique")?.value ?? 0) + uploadedFiles.filter((file) => file.status === "Unique").length;
  const duplicates = (distribution.find((item) => item.name === "Duplicate")?.value ?? 0) + uploadedFiles.filter((file) => file.status === "Duplicate").length;
  const similar = (distribution.find((item) => item.name === "Similar")?.value ?? 0) + uploadedFiles.filter((file) => file.status === "Similar").length;
  return <div className="animate-enter-soft">
    <PageHeading eyebrow="Workspace / Analytics" title="Analytics" description="A closer look at storage efficiency and file classifications in the sample workspace." />
    <DemoNotice compact />
    <section className="mt-5 grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Original storage" value={`${MOCK_STORAGE.originalGb.toFixed(1)} GB`} detail="Sample file footprint" icon={HardDrive} /><StatCard label="Optimized storage" value={`${MOCK_STORAGE.optimizedGb.toFixed(1)} GB`} detail="Illustrative estimate" icon={Zap} /><StatCard label="Files analyzed" value={(MOCK_STORAGE.totalFiles + uploadedFiles.length).toLocaleString()} detail="Includes this-session demos" icon={Files} trend="up" /><StatCard label="Potential savings" value={`${MOCK_STORAGE.savedGb.toFixed(1)} GB`} detail="34.4% of sample storage" icon={Activity} /></section>
    <section className="mt-5 grid grid-cols-1 gap-4 xl:grid-cols-[1.2fr_0.8fr]">
      <div className="rounded-lg border border-border bg-card p-5 sm:p-6"><SectionTitle title="Storage efficiency" detail="Sample storage before and after illustrative optimization" /><div className="mt-6 space-y-5"><EfficiencyBar label="Original storage" value={`${MOCK_STORAGE.originalGb.toFixed(1)} GB`} percent={100} /><EfficiencyBar label="Optimized storage" value={`${MOCK_STORAGE.optimizedGb.toFixed(1)} GB`} percent={(MOCK_STORAGE.optimizedGb / MOCK_STORAGE.originalGb) * 100} /><EfficiencyBar label="Potential savings" value={`${MOCK_STORAGE.savedGb.toFixed(1)} GB`} percent={(MOCK_STORAGE.savedGb / MOCK_STORAGE.originalGb) * 100} /><div className="grid grid-cols-3 gap-3 border-t border-border pt-5"><EfficiencyMetric value="128" label="Exact duplicates" color="text-info" /><EfficiencyMetric value="76" label="Similar files" color="text-warning" /><EfficiencyMetric value="1,044" label="Unique files" color="text-success" /></div></div></div>
      <div className="rounded-lg border border-border bg-card p-5 sm:p-6"><SectionTitle title="File classification" detail="Breakdown of 1,248 sample files" /><div className="flex flex-col items-center gap-5 sm:flex-row sm:justify-center"><div className="h-[220px] w-full max-w-[260px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={distribution} dataKey="value" nameKey="name" cx="50%" cy="50%" innerRadius={66} outerRadius={92} paddingAngle={3} strokeWidth={0}>{distribution.map((entry) => <Cell key={entry.name} fill={entry.color} />)}</Pie><Tooltip contentStyle={{ background: "var(--color-popover)", border: "1px solid var(--color-border)", borderRadius: "8px", fontSize: "12px" }} /></PieChart></ResponsiveContainer><div className="-mt-[142px] mb-[105px] text-center"><p className="font-display text-2xl font-semibold">1,248</p><p className="mt-1 text-[10px] text-muted-foreground">sample files</p></div></div><div className="w-full max-w-[220px] space-y-3">{distribution.map((item) => <div key={item.name} className="flex items-center justify-between gap-3 text-xs"><span className="flex items-center gap-2 text-muted-foreground"><span className="size-2 rounded-full" style={{ backgroundColor: item.color }} />{item.name}</span><span className="font-medium tabular-nums">{item.value.toLocaleString()}</span></div>)}</div></div><p className="mt-2 border-t border-border pt-3 text-[10px] text-muted-foreground">Classification percentages are illustrative sample values.</p></div>
    </section>
    <section className="mt-4 rounded-lg border border-border bg-card p-5 sm:p-6"><SectionTitle title="Storage savings over time" detail="Illustrative cumulative savings, May–October" /><div className="h-[280px] w-full"><ResponsiveContainer width="100%" height="100%"><LineChart data={MOCK_SAVINGS_TREND} margin={{ top: 10, right: 10, left: -18, bottom: 0 }}><CartesianGrid stroke="var(--color-border)" strokeDasharray="3 5" vertical={false} /><XAxis dataKey="month" tickLine={false} axisLine={false} tick={{ fill: "var(--color-muted-foreground)", fontSize: 11 }} /><YAxis tickLine={false} axisLine={false} tick={{ fill: "var(--color-muted-foreground)", fontSize: 11 }} tickFormatter={(value) => `${value} GB`} /><Tooltip contentStyle={{ background: "var(--color-popover)", border: "1px solid var(--color-border)", borderRadius: "8px", fontSize: "12px" }} formatter={(value) => [`${value} GB`, "Potential savings"]} /><Line type="monotone" dataKey="saved" stroke="var(--color-primary)" strokeWidth={2.5} dot={{ fill: "var(--color-primary)", strokeWidth: 0, r: 4 }} activeDot={{ r: 6 }} /></LineChart></ResponsiveContainer></div></section>
    <section className="mt-4 rounded-lg border border-border bg-card p-5 sm:p-6"><SectionTitle title="Activity breakdown" detail="Processed files and duplicates detected over the last 7 days" /><div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4">{MOCK_ACTIVITY.map((entry) => <div key={entry.day} className="rounded-md border border-border p-3"><div className="flex items-center justify-between"><span className="text-xs font-medium">{entry.day}</span><span className="text-[10px] text-muted-foreground">demo</span></div><div className="mt-3 flex justify-between text-[11px] text-muted-foreground"><span>Processed</span><span className="tabular-nums text-foreground">{entry.analyzed}</span></div><div className="mt-1.5 flex justify-between text-[11px] text-muted-foreground"><span>Duplicates</span><span className="tabular-nums text-info">{entry.duplicates}</span></div></div>)}</div></section>
    <section className="mt-4 rounded-lg border border-primary/20 bg-primary/5 p-5 sm:p-6"><div className="flex items-center gap-2"><Sparkles className="size-4 text-primary" /><h2 className="font-display text-base font-semibold">AI Deduplication Insights</h2></div><p className="mt-1 text-xs text-muted-foreground">Illustrative insights based on the sample dataset</p><div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4">{DEMO_INSIGHTS.map((item) => <div key={item.value} className="rounded-md border border-border bg-card/70 p-3.5"><p className="font-display text-xl font-semibold tabular-nums">{item.value}</p><p className="mt-1 text-[11px] leading-5 text-muted-foreground">{item.label}</p></div>)}</div></section>
  </div>;
}

function EfficiencyBar({ label, value, percent }: { label: string; value: string; percent: number }) { return <div><div className="mb-2 flex items-center justify-between text-xs"><span className="text-muted-foreground">{label}</span><span className="font-medium tabular-nums">{value}</span></div><div className="h-2 overflow-hidden rounded-full bg-secondary"><span className="block h-full rounded-full bg-primary" style={{ width: `${percent}%` }} /></div></div>; }
function EfficiencyMetric({ value, label, color }: { value: string; label: string; color: string }) { return <div><p className={`font-display text-lg font-semibold tabular-nums ${color}`}>{value}</p><p className="mt-1 text-[10px] leading-4 text-muted-foreground">{label}</p></div>; }